# NumPy Arrays

In [1]:
import numpy as np

This section will go over examples of numpy arrays to manipulate numerical data. We'll go over some operations to create, modify, and access NumPy arrays. Note that these are in no way holistic and only represent the things that are mostly useful to CIS 105.

## Creating NumPy Arrays from Lists

We start with one-dimensional NumPy arrays. We can create these from lists and simply wrap `np.array` around the list.

In [2]:
some_list = [1, 2, 3]
some_array = np.array(some_list)
some_array

array([1, 2, 3])

Or more succinctly:

In [3]:
some_array = np.array([1, 2, 3])
some_array

array([1, 2, 3])


We can also create two-dimensional or three-dimensional NumPy arrays (though not needed for 105)

In [4]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
three_d_array = np.random.randint(10, size=(2, 3, 4))
three_d_array

array([[[0, 1, 5, 6],
        [4, 4, 5, 8],
        [0, 7, 7, 7]],

       [[1, 8, 6, 6],
        [0, 4, 9, 2],
        [9, 4, 2, 1]]])

## NumPy Array Attributes

We can access useful attributes of NumPy arrays through the `.` notation. Some useful attributes are `ndim`, `shape`, and `size`.

In [6]:
# ndim -> number of dimensions
three_d_array.ndim

3

In [7]:
# shape -> array dimensions
three_d_array.shape

(2, 3, 4)

In [8]:
# size -> total number of elements
three_d_array.size

24

```{tip}
For more attributes, you can explore for yourself by pressing `TAB` after typing in `{name of array}.` Use `?` to find out what each attribute does/is.
```

In [9]:
# for example
three_d_array.cumsum?

## Creating NumPy Arrays using `np.arange`

What if we wanted to create a large numeric array, say 1-2000? It wouldn't be very feasible for us to create this manually by typing out each element inside a list. We could, alternatively use `np.arange` to do this very easily!

In [10]:
some_large_array = np.arange(1, 2001, 1)
some_large_array

array([   1,    2,    3, ..., 1998, 1999, 2000])

The syntax of `np.arange` is `np.arange(start, end, stepsize)`. Note that `start` is inclusive while `end` is exclusive. You may also omit the third argument `stepsize` for this situation as it defaults to `1`.

In [11]:
# 2 stepsize
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [12]:
# negative stepsize
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

## Array Indexing for One-Dimensional Arrays

If you are familiar with doing indexing with Python lists, then indexing in NumPy will feel very familiar.

In [13]:
some_array = np.array(["a", "b", "c", "d", "e"])
some_array

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [14]:
# first element
some_array[0]

'a'

In [15]:
# last element
some_array[-1]

'e'

In [16]:
# third element
some_array[2]

'c'

In [17]:
# second to fourth elements
some_array[1:4]

array(['b', 'c', 'd'], dtype='<U1')

In [18]:
# first four elements
some_array[:4]

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [19]:
# excluding first four elements
some_array[4:]

array(['e'], dtype='<U1')

We can also slice arrays in steps.. The syntax is

```
x[start:end:step]
```

In [20]:
# every second element
some_array[::2]

array(['a', 'c', 'e'], dtype='<U1')

## Array Indexing for Multi-Dimensional Arrays

For multi-dimensional array, we can access elements using a comma-separated tuple of indices (not required for 105)

In [21]:
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
two_d_array[0, 0]

1

In [23]:
two_d_array[2, 0]

7

In [24]:
two_d_array[0, 2]

3

In [25]:
three_d_array

array([[[0, 1, 5, 6],
        [4, 4, 5, 8],
        [0, 7, 7, 7]],

       [[1, 8, 6, 6],
        [0, 4, 9, 2],
        [9, 4, 2, 1]]])

In [26]:
three_d_array[0, 0, 0]

0

## Array Concatenation

We sometimes might also want concatenate together two Numpy arrays. For this task, we can use `np.concatenate` to get the job done. Note that we can also concatenate multi-dimensional arrays but I won't be covering this here.

In [27]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.concatenate([x, y])
z

array([1, 2, 3, 4, 5, 6])